const assetManifest = {
  images: [
    {
      name: 'titlegrey',
      path: './assets/images/titlegrey.png',
      loadOnStart: true,
    },
    {
      name: 'border',
      path: './assets/images/border.png',
      loadOnStart: true,
    },
    {
      name: 'card',
      path: './assets/images/card.png',
      loadOnStart: true,
    },
    {
      name: 'gamebg',
      path: './assets/images/gamebg.png',
      loadOnStart: true,
    },
    {
      name: 'btnBluePressed',
      path: './assets/ui/buttonLong_blue_pressed.png',
      loadOnStart: true,
    },
    {
      name: 'btnBlue',
      path: './assets/ui/buttonLong_blue.png',
      loadOnStart: true,
    },
  ],
  spritesheets: [
    {
      name: 'grassland0',
      path: './assets/spritesheets/tiles_grassland_dense_clear_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'grassland1',
      path: './assets/spritesheets/tiles_grassland_dense_covered_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'grassland2',
      path: './assets/spritesheets/tiles_grassland_sparse_clear_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'grassland3',
      path: './assets/spritesheets/tiles_grassland_sparse_covered_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'forest0',
      path: './assets/spritesheets/tiles_forest_conifer_dense_clear_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'forest1',
      path: './assets/spritesheets/tiles_forest_conifer_sparse_clear_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'forest2',
      path: './assets/spritesheets/tiles_forest_deciduous_dense_clear_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'forest3',
      path: './assets/spritesheets/tiles_forest_deciduous_sparse_clear_green.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'moor0',
      path: './assets/spritesheets/tiles_moor_dense_clear_blue.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'moor1',
      path: './assets/spritesheets/tiles_moor_dense_covered_blue.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'moor2',
      path: './assets/spritesheets/tiles_moor_sparse_clear_blue.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'moor3',
      path: './assets/spritesheets/tiles_moor_sparse_covered_blue.png',
      frameWidth: 210,
      frameHeight: 210,
      loadOnStart: true,
    },
    {
      name: 'humanKing',
      path: './assets/characters/humanKing.png',
      frameWidth: 124,
      frameHeight: 153,
      loadOnStart: true,
    },
    {
      name: 'humanBarbarian',
      path: './assets/characters/barbarian.png',
      frameWidth: 131,
      frameHeight: 133,
      loadOnStart: true,
    },
    {
      name: 'humanMage',
      path: './assets/characters/mage.png',
      frameWidth: 131,
      frameHeight: 137,
      loadOnStart: true,
    },
    {
      name: 'humanKnight',
      path: './assets/characters/knight.png',
      frameWidth: 165,
      frameHeight: 144,
      loadOnStart: true,
    },
    {
      name: 'humanStealth',
      path: './assets/characters/rogue.png',
      frameWidth: 110,
      frameHeight: 135,
      loadOnStart: true,
    },
    {
      name: 'monsterKing',
      path: './assets/characters/skeletonKing.png',
      frameWidth: 124,
      frameHeight: 152,
      loadOnStart: true,
    },
    {
      name: 'monsterKnight',
      path: './assets/characters/witch.png',
      frameWidth: 154,
      frameHeight: 158,
      loadOnStart: true,
    },
    {
      name: 'monsterBarbarian',
      path: './assets/characters/orc.png',
      frameWidth: 129,
      frameHeight: 136,
      loadOnStart: true,
    },
    {
      name: 'monsterMage',
      path: './assets/characters/warlock.png',
      frameWidth: 136,
      frameHeight: 137,
      loadOnStart: true,
    },
    {
      name: 'monsterStealth',
      path: './assets/characters/ghost.png',
      frameWidth: 97,
      frameHeight: 139,
      loadOnStart: true,
    },
    {
      name: 'animalKing',
      path: './assets/characters/pigKing.png',
      frameWidth: 131,
      frameHeight: 98,
      loadOnStart: true,
    },
    {
      name: 'animalStealth',
      path: './assets/characters/mouse.png',
      frameWidth: 114,
      frameHeight: 88,
      loadOnStart: true,
    },
    {
      name: 'animalBarbarian',
      path: './assets/characters/boar.png',
      frameWidth: 136,
      frameHeight: 86,
      loadOnStart: true,
    },
    {
      name: 'animalMage',
      path: './assets/characters/snake.png',
      frameWidth: 122,
      frameHeight: 104,
      loadOnStart: true,
    },
    {
      name: 'animalKnight',
      path: './assets/characters/horse.png',
      frameWidth: 164,
      frameHeight: 134,
      loadOnStart: true,
    },
  ],
};

export default assetManifest;
